const articulos = [
    {
        id:0,
        sexo:'hombre',
        categoria:'casual',
        imagen: 'images/camisa-negra.jpg',
        nombre: 'camisa negra',
        precio: 100
    },
    {
        id:1,
        sexo:'hombre',
        categoria:'casual',
        imagen: 'images/campera-jean.jpg',
        nombre: 'campera de jean',
        precio: 250
    },
    {
        id:2,
        sexo:'mujer',
        categoria:'casual',
        imagen: 'images/remera-roja.jpg',
        nombre: 'remera roja',
        precio: 70
    },
    {   id:3,
        sexo:'mujer',
        categoria:'deportes',
        imagen: 'images/skate.jpg',
        nombre: 'skate',
        precio: 400},
    {   id:4,
        sexo:'mujer',
        categoria:'calzado',
        imagen: 'images/calzado-1.jpg',
        nombre: 'Borcegos',
        precio: 600},
    {   id:5,
        sexo:'hombre',
        categoria:'calzado',
        imagen: 'images/calzado-2.jpg',
        nombre: 'Zapatillas blancas',
        precio: 240},
    {   id:6,
        sexo:'hombre',
        categoria:'calzado',
        imagen: 'images/calzado-3.jpg',
        nombre: 'Zapatillas económicas',
        precio: 80},
    {   id:7,
        /* sexo:'hombre', */
        categoria:'deportes',
        imagen: 'images/fit-1.jpg',
        nombre: 'Soga ejercicio',
        precio: 12},
    {   id:8,
        /* sexo:'hombre', */
        categoria:'deportes',
        imagen: 'images/fit-2.jpg',
        nombre: 'Mancuernas violetas',
        precio: 20},
    {   id:9,
        /* sexo:'hombre', */
        categoria:'deportes',
        imagen: 'images/fit-3.jpg',
        nombre: 'Camilla roja',
        precio: 15},
    {   id:10,
        sexo:'mujer',
        categoria:'underwear',
        imagen: 'images/interior-1.jpg',
        nombre: 'Conjunto deportivo',
        precio: 150},
    {   id:11,
        sexo:'mujer',
        categoria:'underwear',
        imagen: 'images/interior-2.jpg',
        nombre: 'Bra deportivo',
        precio: 110},
    {   id:12,
        sexo:'mujer',
        categoria:'underwear',
        imagen: 'images/interior-3.jpg',
        nombre: 'Bucaneras',
        precio: 70},
    {   id:13,
        sexo:'mujer',
        categoria:'underwear',
        imagen: 'images/interior-4.jpg',
        nombre: 'Calzón blanco',
        precio: 90},
    {   id:14,
        sexo:'hombre',
        categoria:'underwear',
        imagen: 'images/interior-5.jpg',
        nombre: 'Boxer gris',
        precio: 130},
    {   id:15,
        sexo:'mujer',
        categoria:'perfumes',
        imagen: 'images/perfume-1.jpg',
        nombre: 'Perfume vainilla',
        precio: 200},
    {   id:16,
        sexo:'mujer',
        categoria:'perfumes',
        imagen: 'images/perfume-2.jpg',
        nombre: 'Sand perfume',
        precio: 200},
    {   id:17,
        sexo:'mujer',
        categoria:'perfumes',
        imagen: 'images/perfume-3.jpg',
        nombre: 'Flower perfume',
        precio: 200},
]